### ISSUE TITLE
Expo Managed app support

### ISSUE THREAD

**Issue by fabiofcferreira** [enesozturk/react-native-hold-menu#81]
**Describe the bug**
Upon following the instructions in this package's README and also the dependencies instructions, I've come up to this error:
```
TypeError: (0, _expoModulesCore.requireNativeModule) is not a function. (In '(0, _expoModulesCore.requireNativeModule)('ExpoHaptics')', '(0, _expoModulesCore.requireNativeModule)' is undefined)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://192.168.1.100:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:284752:3 in global code
```

**To Reproduce**
1. `yarn add react-native-hold-menu`
2. `npx expo install react-native-reanimated`
3. `expo install react-native-gesture-handler`
4. `npx expo install expo-blur`
5. `npx expo install expo-haptics`

**Expected behavior**
Hold menu working

**Actual behavior**
App doesn't run with the following error being displayed: `TypeError: (0, _expoModulesCore.requireNativeModule) is not a function. (In '(0, _expoModulesCore.requireNativeModule)`.

**Screenshots**
![image](https://user-images.githubusercontent.com/11786424/193299357-9ebe77d3-d993-45e8-8d3a-10dffe638566.png)

**Package versions**
 - React: 17.0.1
 - React Native: 0.64.3
 - React Native Reanimated: ~2.3.1
 - React Native Hold Menu: 0.1.5
 - Expo: ~44.0.0
 - Expo Haptics: ~11.1.0
 - Expo Blur: ~11.0.0

**Additional context**
From my understanding, this could be an issue with [expo-modules-core](https://github.com/expo/expo/tree/main/packages/expo-modules-core) not supporting expo managed apps yet - hence the API documentation for setup not being valid.

However, if that is true this package could have a more clear description of what's going on with the expo compability. It says it's compatible but it's not clear if it supports bare, managed or both types of apps.

**Comment by PavelTishenko** [comment]
Any updates ?

**Comment by enesozturk** [comment]
Hey @fabiofcferreira, this library's example app is created with Expo managed workflow. So it's supporting the Expo already. You could reference the example app [here](https://github.com/enesozturk/react-native-hold-menu/tree/main/example).

Maybe it's because they are moved `expo-haptics` to JSI, it's not working properly with SDK 44. But this is just a thought I'll need to check the previous versions of Expo. ref: https://blog.expo.dev/expo-sdk-45-f4e332954a68
